---
- name: Enable and start {{ unit }}
  ansible.builtin.systemd:
    name: "{{ unit }}"
    enabled: true
    state: started
  when: run_on == "all" and user_unit is not defined

- name: Disable {{ unit }}
  ansible.builtin.systemd:
    name: "{{ unit }}"
    enabled: false
  when: run_on != "all" and user_unit is not defined

- name: "Add to trusted unit list: {{ unit }}"
  ansible.builtin.lineinfile:
    dest: /etc/nmtrust/trusted_units
    state: present
    line: "{{ unit }}"
  when: run_on == "trusted" and user_unit is not defined

- name: "Remove from trusted unit list: {{ unit }}"
  ansible.builtin.lineinfile:
    dest: /etc/nmtrust/trusted_units
    state: absent
    line: "{{ unit }}"
  when: run_on != "trusted" and user_unit is not defined

- name: "Enable and start user unit: {{ unit }}"
  ansible.builtin.systemd:
    name: "{{ unit }}"
    enabled: true
    state: started
    scope: user
  become: true
  become_user: "{{ user.name }}"
  environment:
    XDG_RUNTIME_DIR: "/run/user/{{ user.uid }}"
  when: run_on == "all" and user_unit is defined and user_unit

- name: "Disable user unit: {{ unit }}"
  ansible.builtin.systemd:
    name: "{{ unit }}"
    enabled: false
    scope: user
  become: true
  become_user: "{{ user.name }}"
  environment:
    XDG_RUNTIME_DIR: "/run/user/{{ user.uid }}"
  when: run_on != "all" and user_unit is defined and user_unit

- name: "Add user unit to trusted unit list: {{ unit }}"
  ansible.builtin.lineinfile:
    dest: /etc/nmtrust/trusted_units
    state: present
    line: "{{ unit }},user:{{ user.name }}"
  when: run_on == "trusted" and user_unit is defined and user_unit

- name: "Remove user unit from trusted unit list: {{ unit }}"
  ansible.builtin.lineinfile:
    dest: /etc/nmtrust/trusted_units
    state: absent
    line: "{{ unit }},user:{{ user.name }}"
  when: run_on != "trusted" and user_unit is defined and user_unit
