---
- name: Install weechat
  community.general.pacman:
    name: weechat
    state: present

- name: Jail weechat
  ansible.builtin.file:
    src: /usr/bin/firejail
    dest: /usr/local/bin/weechat
    state: link
  tags:
    - firejail

- name: Install dunst
  community.general.pacman:
    name: dunst
    state: present
