---
- name: Install PostgreSQL
  community.general.pacman:
    name: postgresql
    state: present

- name: Install psycopg2
  community.general.pacman:
    name: python-psycopg2
    state: present

- name: Create postgres data root
  ansible.builtin.file:
    path: "{{ postgresql.root }}/data"
    state: directory
    owner: postgres
    group: postgres
    mode: "0700"

- name: Initialize database cluster
  ansible.builtin.command:
    cmd: initdb --locale en_US.UTF-8 -E UTF8 -D {{ postgresql.root }}/data
    creates: "{{ postgresql.root }}/data/postgresql.conf"
  become: true
  become_user: postgres

- name: Disable synchronous commits
  ansible.builtin.lineinfile:
    dest: "{{ postgresql.root }}/data/postgresql.conf"
    regexp: ^synchronous_commit
    state: present
    line: "synchronous_commit = off"
  notify:
    - Restart postgresql

- name: Create service override directory
  ansible.builtin.file:
    path: /etc/systemd/system/postgresql.service.d
    state: directory
    mode: "0755"

- name: Push service override file
  ansible.builtin.template:
    src: postgresql-override.conf.j2
    dest: /etc/systemd/system/postgresql.service.d/override.conf
    mode: "0644"
  notify:
    - Reload systemd config
    - Restart postgresql

- name: Disable and stop PostgreSQL
  ansible.builtin.service:
    name: postgresql.service
    enabled: false
    state: stopped
  when: postgresql is not defined or postgresql.enable is not defined or not postgresql.enable

- name: Enable and start PostgreSQL
  ansible.builtin.service:
    name: postgresql.service
    enabled: true
    state: started
  when: postgresql is defined and postgresql.enable is defined and postgresql.enable

- name: Create the PostgreSQL user
  community.postgresql.postgresql_user:
    name: "{{ user.name }}"
    role_attr_flags: CREATEDB,NOSUPERUSER
  when: postgresql is defined and postgresql.enable is defined and postgresql.enable
