---
- name: Install chrony
  community.general.pacman:
    name: chrony
    state: present

- name: Push chrony configuration file
  ansible.builtin.copy:
    src: chrony.conf
    dest: /etc/chrony.conf
    mode: "0644"
  notify:
    - Restart chrony

- name: Enable and start chrony
  ansible.builtin.service:
    name: chronyd.service
    enabled: true
    state: started

- name: Push chrony NetworkManager dispatcher
  ansible.builtin.copy:
    src: chrony-dispatcher.sh
    dest: /etc/NetworkManager/dispatcher.d/70-chrony
    mode: "0755"
