---
- name: Reload systemd config
  ansible.builtin.systemd:
    daemon_reload: true

- name: Reload user systemd config
  ansible.builtin.systemd:
    daemon_reload: true
    scope: user
  become: true
  become_user: "{{ user.name }}"
  environment:
    XDG_RUNTIME_DIR: "/run/user/{{ user.uid }}"
