---
- name: Install virtualenv and virtualenvwrapper
  community.general.pacman:
    name: python-virtualenvwrapper
    state: present

- name: Create system environment group
  ansible.builtin.group:
    name: env
    state: present

- name: Add user to system environment group
  ansible.builtin.user:
    name: "{{ user.name }}"
    groups: env
    append: true
  tags:
    - user

- name: Create system environment dir
  ansible.builtin.file:
    path: /usr/local/env
    state: directory
    group: env
    mode: "02775"
