---
- name: Restart iptables
  ansible.builtin.service:
    name: iptables.service
    state: restarted

- name: Restart ip6tables
  ansible.builtin.service:
    name: ip6tables.service
    state: restarted
