---
- name: Restart tlp
  ansible.builtin.service:
    name: tlp.service
    state: restarted

- name: Restart power monitor
  ansible.builtin.service:
    name: power_monitor.service
    state: restarted
