---
- name: Install go
  community.general.pacman:
    name: go
    state: present

- name: Create system go group
  ansible.builtin.group:
    name: golang
    state: present

- name: Add user to system golang group
  ansible.builtin.user:
    name: "{{ user.name }}"
    groups: golang
    append: true
  tags:
    - user

- name: Create system go dir
  ansible.builtin.file:
    path: /usr/local/go
    state: directory
    group: golang
    mode: "0775"
