---
- name: Install RedShift and dependencies
  community.general.pacman:
    name:
      - librsvg
      - python-gobject
      - python-xdg
      - redshift
    state: present

- name: Jail RedShift
  ansible.builtin.file:
    src: /usr/bin/firejail
    dest: /usr/local/bin/redshift
    state: link
  tags:
    - firejail

- name: Jail RedShift GTK
  ansible.builtin.file:
    src: /usr/bin/firejail
    dest: /usr/local/bin/redshift-gtk
    state: link
  tags:
    - firejail

- name: Push RedShift GTK firejail profile
  ansible.builtin.copy:
    src: firejail/redshift-gtk.profile
    dest: /usr/local/etc/firejail/redshift-gtk.profile
    mode: "0644"
  notify:
    - Activate firejail profiles
  tags:
    - firejail
