---
- name: Install mpv
  community.general.pacman:
    name: mpv
    state: present

- name: Jail mpv
  ansible.builtin.file:
    src: /usr/bin/firejail
    dest: /usr/local/bin/mpv
    state: link
  tags:
    - firejail

- name: Push play script
  ansible.builtin.copy:
    src: play.sh
    dest: /usr/local/bin/play
    mode: "0755"
