---
- name: Install MTR
  community.general.pacman:
    name: mtr
    state: present

- name: Install net-tools
  community.general.pacman:
    name: net-tools
    state: present

- name: Install bind-tools
  community.general.pacman:
    name: bind-tools
    state: present

- name: Install whois
  community.general.pacman:
    name: whois
    state: present

- name: Install netcat
  community.general.pacman:
    name: openbsd-netcat
    state: present

- name: Install lftp
  community.general.pacman:
    name: lftp
    state: present

- name: Install nmap
  community.general.pacman:
    name: nmap
    state: present

- name: Install tcpdump
  community.general.pacman:
    name: tcpdump
    state: present

- name: Install sshuttle
  community.general.pacman:
    name: sshuttle
    state: present

- name: Install wireshark
  community.general.pacman:
    name: wireshark-qt
    state: present

- name: Add user to wireshark group
  ansible.builtin.user:
    name: "{{ user.name }}"
    groups: wireshark
    append: true
  tags:
    - user

- name: Install socat
  community.general.pacman:
    name: socat
    state: present

- name: Install nethogs
  community.general.pacman:
    name: nethogs
    state: present

- name: Install bmon
  community.general.pacman:
    name: bmon
    state: present

- name: Install speedtest-cli
  community.general.pacman:
    name: speedtest-cli
    state: present

- name: Install spiped
  community.general.pacman:
    name: spiped
    state: present

- name: Install wireguard and kernel modules
  community.general.pacman:
    name: wireguard-tools
    state: present

- name: Install wget
  community.general.pacman:
    name: wget
    state: present
