---
- name: Install GNOME Display Manager (GDM)
  community.general.pacman:
    name: gdm
    state: present

- name: Enable GDM
  ansible.builtin.service:
    name: gdm.service
    enabled: true

- name: Creating DConf configuration profile
  ansible.builtin.copy:
    src: profile/gdm
    dest: /etc/dconf/profile/gdm
    mode: "0644"

- name: Creating gdm.d directory for DConf
  ansible.builtin.file:
    path: /etc/dconf/db/gdm.d
    state: directory
    mode: "0755"

- name: Configuring GDM
  ansible.builtin.template:
    src: gdm.d/00-spark.j2
    dest: /etc/dconf/db/gdm.d/00-spark
    mode: "0644"
  notify: Update DConf database
