---
- name: Install openresolv
  community.general.pacman:
    name: openresolv
    state: present

- name: Push resolvconf.conf
  ansible.builtin.template:
    src: resolvconf.conf.j2
    dest: /etc/resolvconf.conf
    mode: "0644"

- name: Push NetworkManager openresolv config.
  ansible.builtin.copy:
    src: rc-manager.conf
    dest: /etc/NetworkManager/conf.d/20-rc-manager.conf
    mode: "0644"
