---
- name: Creating DConf database directory
  ansible.builtin.file:
    path: /etc/dconf/db
    state: directory
    mode: "0755"
    recurse: true

- name: Creating DConf profile directory
  ansible.builtin.file:
    path: /etc/dconf/profile
    state: directory
    mode: "0755"
    recurse: true
