---
- name: Install rtorrent
  community.general.pacman:
    name: rtorrent
    state: present

- name: Jail rtorrent
  ansible.builtin.file:
    src: /usr/bin/firejail
    dest: /usr/local/bin/rtorrent
    state: link
  tags:
    - firejail
