---
- name: Install Unbound
  community.general.pacman:
    name: unbound
    state: present

- name: Download root hints
  ansible.builtin.get_url:
    url: https://www.internic.net/domain/named.cache
    dest: /etc/unbound/root.hints
    force: true
    mode: "0644"

- name: Verify unbound resolvconf config file exists
  ansible.builtin.copy:
    content: ""
    dest: /etc/unbound/resolvconf.conf
    force: false
    mode: "0644"

- name: Copy Unbound configuration file
  ansible.builtin.template:
    src: unbound.conf.j2
    dest: /etc/unbound/unbound.conf
    mode: "0644"
  notify:
    - Restart unbound

- name: Enable and start Unbound
  ansible.builtin.service:
    name: unbound.service
    enabled: true
    state: started

- name: Push Unbound root hits update service file
  ansible.builtin.copy:
    src: roothints.service
    dest: /etc/systemd/system/roothints.service
    mode: "0644"
  notify:
    - Reload systemd config

- name: Push Unbound root hits update timer file
  ansible.builtin.copy:
    src: roothints.timer
    dest: /etc/systemd/system/roothints.timer
    mode: "0644"
  notify:
    - Reload systemd config
    - Restart roothints

- name: Include nmtrust unit tasks
  ansible.builtin.include_tasks: roles/nmtrust/tasks/unit.yml
  vars:
    unit: roothints.timer
    run_on: "{{ unbound.roothints_update }}"
