---
- name: Install Fedora systemd-oomd configuration
  kewlfft.aur.aur:
    name: systemd-oomd-defaults
  become: true
  become_user: "{{ aur.user }}"
  notify:
    - Reload systemd config
  tags:
    - aur

- name: Enable and start systemd-oomd
  ansible.builtin.service:
    name: systemd-oomd.service
    enabled: true
    state: started
