---
- name: Install bluetooth libraries and tools
  community.general.pacman:
    name:
      - bluez
      - bluez-libs
      - bluez-utils
      - blueman
    state: present
  notify:
    - Restart pulse as user

- name: Do not auto power on the bluetooth device
  ansible.builtin.lineinfile:
    dest: /etc/bluetooth/main.conf
    state: present
    line: "AutoEnable=false"

- name: Unblock the bluetooth service
  ansible.builtin.service:
    name: rfkill-block@bluetooth.service
    enabled: false
    state: stopped
  when: not bluetooth.disable

- name: Enable and start the bluetooth service
  ansible.builtin.service:
    name: bluetooth.service
    enabled: true
    state: started
  when: not bluetooth.disable

- name: Disable and stop the bluetooth service
  ansible.builtin.service:
    name: bluetooth.service
    enabled: false
    state: stopped
  when: bluetooth.disable

- name: Block the bluetooth service
  ansible.builtin.service:
    name: rfkill-block@bluetooth.service
    enabled: true
    state: started
  when: bluetooth.disable
