---
- name: Install android-tools
  community.general.pacman:
    name: android-tools
    state: present

- name: Install android-udev
  community.general.pacman:
    name: android-udev
    state: present

- name: "Add user to adbusers group: {{ user.name }}"
  ansible.builtin.user:
    name: "{{ user.name }}"
    groups: adbusers
    append: true
  tags:
    - user
