---
- name: Install Xorg
  community.general.pacman:
    name: xorg-server
    state: present

- name: Install Xinit
  community.general.pacman:
    name: xorg-xinit
    state: present

- name: Install xmodmap
  community.general.pacman:
    name: xorg-xmodmap
    state: present

- name: Install xdpyinfo
  community.general.pacman:
    name: xorg-xdpyinfo
    state: present

- name: Install xev
  community.general.pacman:
    name: xorg-xev
    state: present

- name: Install xorg-sessreg
  community.general.pacman:
    name: xorg-sessreg
    state: present

- name: Install xorg-xwininfo
  community.general.pacman:
    name: xorg-xwininfo
    state: present

- name: Install xautomation
  community.general.pacman:
    name: xautomation
    state: present

- name: Install xcalib
  community.general.pacman:
    name: xcalib
    state: present

- name: Install video driver(s)
  community.general.pacman:
    name: "{{ video_drivers }}"
    state: present
  when: video_drivers is defined

- name: Add user to video group
  ansible.builtin.user:
    name: "{{ user.name }}"
    groups: video
    append: true
  tags:
    - user

- name: Enable middle-click scrolling
  ansible.builtin.template:
    src: 30-scroll.conf
    dest: /etc/X11/xorg.conf.d/30-scroll.conf
    mode: "0644"
  when: libinput.middle_click_scroll is defined
  tags:
    - libinput

- name: Remap mouse buttons
  ansible.builtin.template:
    src: 30-button_mapping.conf
    dest: /etc/X11/xorg.conf.d/30-button_mapping.conf
    mode: "0644"
  when: libinput.button_mapping is defined
  tags:
    - libinput

- name: Include sxhkd tasks
  ansible.builtin.include_tasks: sxhkd.yml
- name: Include unclutter tasks
  ansible.builtin.include_tasks: unclutter.yml
- name: Include autorandr tasks
  ansible.builtin.include_tasks: autorandr.yml
- name: Include XDG tasks
  ansible.builtin.include_tasks: xdg.yml
