---
- name: Install xdg-user-dirs
  community.general.pacman:
    name: xdg-user-dirs
    state: present
  tags:
    - xdg

- name: Create user directories
  ansible.builtin.command: /usr/bin/xdg-user-dirs-update
  become: true
  become_user: "{{ user.name }}"
  changed_when: false
  tags:
    - xdg

- name: Install perl-file-mimeinfo
  community.general.pacman:
    name: perl-file-mimeinfo
    state: present
  tags:
    - xdg
