---
- name: Install sysstat
  community.general.pacman:
    name: sysstat
    state: present

- name: Install glances
  community.general.pacman:
    name: glances
    state: present

- name: Install btop
  community.general.pacman:
    name: btop
    state: present

- name: Install htop
  community.general.pacman:
    name: htop
    state: present

- name: Install lsof
  community.general.pacman:
    name: lsof
    state: present

- name: Install strace
  community.general.pacman:
    name: strace
    state: present

- name: Install smartmontools
  community.general.pacman:
    name: smartmontools
    state: present

- name: Install progress
  community.general.pacman:
    name: progress
    state: present
