---
- name: Install taskwarrior
  community.general.pacman:
    name: task
    state: present

- name: Install timewarrior
  community.general.pacman:
    name: timew
    state: present
  notify:
    - Refresh holidays

- name: Install taskopen
  kewlfft.aur.aur:
    name: taskopen
  become: true
  become_user: "{{ aur.user }}"
  tags:
    - aur
