---
- name: Install hostsctl
  kewlfft.aur.aur:
    name: hostsctl
  become: true
  become_user: "{{ aur.user }}"
  tags:
    - aur

- name: Push hostsctl config
  ansible.builtin.template:
    src: hostsctl.conf.j2
    dest: /etc/hostsctl.conf
    mode: "0644"

- name: Update hostsctl
  ansible.builtin.command: hostsctl update
  changed_when: true
