---
- name: Copy mtrack-git configuration file
  ansible.builtin.copy:
    src: 50-mtrack-git.conf
    dest: /etc/X11/xorg.conf.d/50-mtrack-git.conf
    mode: "0644"

- name: Install xf86-input-mtrack-git
  kewlfft.aur.aur:
    name: xf86-input-mtrack-git
  become: true
  become_user: "{{ aur.user }}"
  tags:
    - aur
