---
- name: Install LibreOffice
  community.general.pacman:
    name: libreoffice-fresh
    state: present

- name: Jail LibreOffice
  ansible.builtin.file:
    src: /usr/bin/firejail
    dest: /usr/local/bin/libreoffice
    state: link
  tags:
    - firejail

- name: Verify LibreOffice firejail local profile exists
  ansible.builtin.copy:
    content: ""
    dest: /etc/firejail/libreoffice.local
    force: false
    mode: "0644"
  tags:
    - firejail

- name: Restrict LibreOffice network access
  ansible.builtin.lineinfile:
    dest: /etc/firejail/libreoffice.local
    regexp: "^net"
    line: "net none"
  tags:
    - firejail

- name: Restrict LibreOffice access to /etc
  ansible.builtin.lineinfile:
    dest: /etc/firejail/libreoffice.local
    regexp: "^private-etc"
    line: "private-etc firejail,libreoffice,fonts,passwd"
  tags:
    - firejail

- name: Install enscript
  community.general.pacman:
    name: enscript
    state: present

- name: Install Simple Scan
  community.general.pacman:
    name: simple-scan
    state: present

- name: Install pandoc
  community.general.pacman:
    name: pandoc-cli
    state: present

- name: Install texlive-basic
  community.general.pacman:
    name: texlive-basic
    state: present

- name: Install texlive-latexextra
  community.general.pacman:
    name: texlive-latexextra
    state: present

- name: Install texlive-binextra
  community.general.pacman:
    name: texlive-binextra
    state: present

- name: Install qalculate
  community.general.pacman:
    name: qalculate-gtk
    state: present

- name: Install GNU Plot
  community.general.pacman:
    name: gnuplot
    state: present

- name: Install xsv
  kewlfft.aur.aur:
    name: xsv
  become: true
  become_user: "{{ aur.user }}"
  tags:
    - aur

- name: Install epy
  kewlfft.aur.aur:
    name: epy-git
  become: true
  become_user: "{{ aur.user }}"
  tags:
    - aur

- name: Install csvkit
  community.general.pacman:
    name: csvkit
    state: present
