---
- name: Install calibre
  community.general.pacman:
    name: calibre
    state: present

- name: Jail calibre
  ansible.builtin.file:
    src: /usr/bin/firejail
    dest: /usr/local/bin/calibre
    state: link
  tags:
    - firejail

- name: Jail ebook-viewer
  ansible.builtin.file:
    src: /usr/bin/firejail
    dest: /usr/local/bin/ebook-viewer
    state: link
  tags:
    - firejail

- name: Install libgourou
  kewlfft.aur.aur:
    name: gourou
  become: true
  become_user: "{{ aur.user }}"
  tags:
    - aur
