---
- name: Install linux-hardened
  community.general.pacman:
    name:
      - linux-hardened
      - linux-hardened-headers
    state: present
  notify:
    - Rebuild grub

- name: Enable unprivileged containers for non-root users
  ansible.builtin.copy:
    src: 99-userns.conf
    dest: /etc/sysctl.d/99-userns.conf
    mode: "0644"
  notify:
    - Reload sysctl
  when: hardened is defined and hardened.enable_namespaces
