---
- name: Install Okular
  pacman:
    name: okular
    state: present
  tags:
    - okular

- name: Jail Okular
  file:
    src: /usr/bin/firejail
    dest: /usr/local/bin/okular
    state: link
  tags:
    - okular
    - firejail

- name: Verify Okular firejail local profile exists
  copy:
    content: ""
    dest: /etc/firejail/okular.local
    force: false
  tags:
    - okular
    - firejail

- name: Restrict Okular network access
  lineinfile:
    dest: /etc/firejail/okular.local
    regexp: "^net"
    line: "net none"
  tags:
    - okular
    - firejail

- name: Install Zathura and dependencies
  pacman:
    name:
      - zathura-cb
      - zathura-pdf-mupdf
      - zathura-ps
    state: present
  tags:
    - zathura

- name: Set Zathura as default PDF viewer
  lineinfile:
    dest: /etc/xdg/mimeapps.list
    regexp: "^application/pdf"
    state: present
    line: "application/pdf=org.pwmt.zathura-pdf-mupdf.desktop"
  tags:
    - zathura

- name: Jail Zathura
  file:
    src: /usr/bin/firejail
    dest: /usr/local/bin/zathura
    state: link
  tags:
    - zathura
    - firejail


- name: Install pdfgrep
  pacman:
    name: pdfgrep
    state: present
  tags:
    - pdfgrep

- name: Install OCRmyPDF
  kewlfft.aur.aur:
    name: ocrmypdf
  become: yes
  become_user: "{{ aur.user }}"
  tags:
    - ocrmypdf
    - aur

- name: Install tesseract-data-eng
  pacman:
    name: tesseract-data-eng
    state: present
  tags:
    - ocrmypdf
