---
- name: Install dictd
  community.general.pacman:
    name: dictd
    state: present

- name: Install flex
  community.general.pacman:
    name: flex
    state: present

- name: Install GNU Collaborative International Dictionary of English
  kewlfft.aur.aur:
    name: dict-gcide
    use: makepkg
    skip_pgp_check: true
  become: true
  become_user: "{{ aur.user }}"
  tags:
    - aur

- name: Install WordNet database
  kewlfft.aur.aur:
    name: wordnet-dictd
  become: true
  become_user: "{{ aur.user }}"
  tags:
    - aur

- name: Install Moby thesaurus
  kewlfft.aur.aur:
    name: dict-moby-thesaurus
  become: true
  become_user: "{{ aur.user }}"
  tags:
    - aur

- name: Enable and start dictd
  ansible.builtin.service:
    name: dictd.service
    enabled: true
    state: started
