---
- name: Install transmission
  community.general.pacman:
    name: transmission-gtk
    state: present

- name: Jail transmission
  ansible.builtin.file:
    src: /usr/bin/firejail
    dest: /usr/local/bin/transmission-gtk
    state: link
  tags:
    - firejail
