---
- name: Install GOESImage
  kewlfft.aur.aur:
    name: goesimage
  become: true
  become_user: "{{ aur.user }}"
  tags:
    - aur

- name: Push GOESImage service file
  ansible.builtin.template:
    src: goesimage.service.j2
    dest: /etc/systemd/user/goesimage.service
    mode: "0644"
  notify:
    - Reload systemd config

- name: Push GOESImage timer file
  ansible.builtin.template:
    src: goesimage.timer.j2
    dest: /etc/systemd/user/goesimage.timer
    mode: "0644"
  notify:
    - Reload systemd config
    - Restart GOESImage

- name: Include nmtrust unit tasks
  ansible.builtin.include_tasks: roles/nmtrust/tasks/unit.yml
  vars:
    unit: goesimage.timer
    run_on: "{{ goesimage.run_on }}"
    user_unit: true
