---
- name: Include TLP tasks
  ansible.builtin.include_tasks: tlp.yml
  when: power_management is defined and power_management == "tlp"

- name: Include tuned tasks
  ansible.builtin.include_tasks: tuned.yml
  when: power_management is defined and power_management == "tuned"

- name: Include Framework tasks
  ansible.builtin.include_tasks: framework.yml
  when: power_management is defined and power_management == "tuned" and ansible_system_vendor == "Framework"

- name: Install x86_energy_perf_policy
  community.general.pacman:
    name: x86_energy_perf_policy
    state: present

- name: Copy touchpad configuration file
  ansible.builtin.copy:
    src: 30-touchpad.conf
    dest: /etc/X11/xorg.conf.d/30-touchpad.conf
    mode: "0644"
  tags:
    - libinput

- name: Copy logind configuration file
  ansible.builtin.copy:
    src: logind.conf
    dest: /etc/systemd/logind.conf
    mode: "0644"

- name: Install poweralertd
  kewlfft.aur.aur:
    name: poweralertd
  become: true
  become_user: "{{ aur.user }}"
  tags:
    - aur

- name: Enable and start poweralertd
  ansible.builtin.systemd:
    name: poweralertd.service
    scope: user
    enabled: true
    state: started
  become: true
  become_user: "{{ user.name }}"
  environment:
    XDG_RUNTIME_DIR: "/run/user/{{ user.uid }}"
  tags:
    - aur

- name: Install powertop
  community.general.pacman:
    name: powertop
    state: present

- name: Install powerstat
  kewlfft.aur.aur:
    name: powerstat
  become: true
  become_user: "{{ aur.user }}"
  tags:
    - aur

- name: Install cmake for battery-stats
  community.general.pacman:
    name: cmake
    state: present

- name: Install battery-stats
  kewlfft.aur.aur:
    name: battery-stats-git
  become: true
  become_user: "{{ aur.user }}"
  tags:
    - aur

- name: Install battop
  kewlfft.aur.aur:
    name: battop
  become: true
  become_user: "{{ aur.user }}"
  tags:
    - aur
