---
- name: Install TLP
  community.general.pacman:
    name:
      - ethtool
      - tlp
      - tlp-rdw
    state: present
  tags:
    - tlp

- name: Push TLP battery threshold config
  ansible.builtin.copy:
    src: tlp/20-battery.conf
    dest: /etc/tlp.d/
    mode: "0644"
  notify:
    - Restart tlp
  tags:
    - tlp

- name: Push TLP radio device config
  ansible.builtin.copy:
    src: tlp/20-rdw.conf
    dest: /etc/tlp.d/
    mode: "0644"
  notify:
    - Restart tlp
  tags:
    - tlp

- name: Push TLP PCIe config
  ansible.builtin.copy:
    src: tlp/20-pcie.conf
    dest: /etc/tlp.d/
    mode: "0644"
  notify:
    - Restart tlp
  tags:
    - tlp

- name: Mask systemd radio service
  ansible.builtin.systemd:
    name: systemd-rfkill.service
    masked: true
  tags:
    - tlp

- name: Mask systemd radio socket
  ansible.builtin.systemd:
    name: systemd-rfkill.socket
    masked: true
  tags:
    - tlp

- name: Enable TLP
  ansible.builtin.service:
    name: tlp.service
    enabled: true
  tags:
    - tlp
