---
- name: Install TuneD
  community.general.pacman:
    name: tuned-ppd
    state: present
  tags:
    - tuned

- name: Enable and start TuneD
  ansible.builtin.service:
    name: tuned.service
    enabled: true
    state: started
  tags:
    - tuned

- name: Install power monitor script
  ansible.builtin.copy:
    src: power_monitor.sh
    dest: /usr/local/bin/
    mode: "0755"
  notify:
    - Restart power monitor
  tags:
    - tuned

- name: Copy power monitor service
  ansible.builtin.copy:
    src: power_monitor.service
    dest: /etc/systemd/system/
    mode: "0644"
  notify:
    - Reload systemd config
    - Restart power monitor
  tags:
    - tuned

- name: Enable and start power monitor service
  ansible.builtin.service:
    name: power_monitor.service
    enabled: true
    state: started
  tags:
    - tuned
