---
- name: Install pass
  community.general.pacman:
    name: pass
    state: present

- name: Install pass-otp
  community.general.pacman:
    name: pass-otp
    state: present

- name: Install rofi-pass
  community.general.pacman:
    name: rofi-pass
    state: present
  tags:
    - rofi

- name: Install pass-update
  kewlfft.aur.aur:
    name: pass-update
    use: makepkg
    skip_pgp_check: true
  become: true
  become_user: "{{ aur.user }}"
  tags:
    - aur
