---
- name: Install i3
  community.general.pacman:
    name:
      - i3-wm
      - i3blocks
      - i3lock
      - i3status
    state: present

- name: Install py3status
  community.general.pacman:
    name: py3status
    state: present

- name: Install wmfocus
  community.general.pacman:
    name: wmfocus
    state: present

- name: Verify that default applications file exists
  ansible.builtin.copy:
    content: ""
    dest: /etc/xdg/mimeapps.list
    force: false
    mode: "0644"

- name: Verify header in default applications file
  ansible.builtin.lineinfile:
    dest: /etc/xdg/mimeapps.list
    state: present
    line: "[Default Applications]"
    insertbefore: BOF

- name: Include rofi tasks
  ansible.builtin.include_tasks: rofi.yml
