---
- name: Install rofi
  pacman: name=rofi state=present
  tags:
    - rofi

- name: Install rofi-pass
  aur: name=rofi-pass-git user={{ user.name }}
  tags:
    - aur
    - rofi

- name: Install i3-wm for rofi window switching
  pacman: name=i3-wm state=present
  tags:
    - rofi

- name: Push rofi browser chooser
  template: src=browser.sh.j2 dest=/usr/local/bin/browser mode=0755
  tags:
    - rofi
