---
- name: Install rofi
  community.general.pacman:
    name: rofi
    state: present
  tags:
    - rofi

- name: Install i3-wm for rofi window switching
  community.general.pacman:
    name: i3-wm
    state: present
  tags:
    - rofi
