---
- name: Install vagrant
  community.general.pacman:
    name: vagrant
    state: present

- name: Install consul
  community.general.pacman:
    name: consul
    state: present

- name: Install terraform
  community.general.pacman:
    name: terraform
    state: present

- name: Install vault
  community.general.pacman:
    name: vault
    state: present

- name: Install nomad
  kewlfft.aur.aur:
    name: nomad
  become: true
  become_user: "{{ aur.user }}"
  tags:
    - aur
