---
- name: Install GNOME
  community.general.pacman:
    name:
      - gnome
      - gnome-extra
      - gnome-tweaks
      - xorg-server-xwayland
    state: present

- name: Include DConf tasks
  ansible.builtin.include_tasks: dconf.yml
- name: Include GTK tasks
  ansible.builtin.include_tasks: gtk.yml
- name: Include GNOME Shell tasks
  ansible.builtin.include_tasks: gnome_shell.yml
- name: Include online accounts tasks
  ansible.builtin.include_tasks: online_accounts.yml
