---
- name: Install Tarsnap
  community.general.pacman:
    name: tarsnap
    state: present

- name: Copy default Tarsnap config
  ansible.builtin.copy:
    src: /etc/tarsnap/tarsnap.conf.sample
    dest: /etc/tarsnap/tarsnap.conf
    mode: "0644"

- name: Create Tarsnap cache dir
  ansible.builtin.file:
    path: /usr/local/tarsnap-cache
    state: directory
    mode: "0700"

- name: Humanize Tarsnap numbers
  ansible.builtin.lineinfile:
    dest: /etc/tarsnap/tarsnap.conf
    state: present
    line: humanize-numbers

- name: Install tarsnapper
  kewlfft.aur.aur:
    name: tarsnapper
  become: true
  become_user: "{{ aur.user }}"
  tags:
    - aur

- name: Create Tarsnapper config include dir
  ansible.builtin.file:
    path: /usr/local/etc/tarsnapper.d/
    state: directory
    mode: "0755"

- name: Push Tarsnapper config
  ansible.builtin.template:
    src: tarsnapper.conf.j2
    dest: /usr/local/etc/tarsnapper.conf
    mode: "0644"

- name: Push Tarsnapper service file
  ansible.builtin.template:
    src: tarsnapper.service.j2
    dest: /etc/systemd/system/tarsnapper.service
    mode: "0644"
  notify:
    - Reload systemd config

- name: Push Tarsnapper timer file
  ansible.builtin.template:
    src: tarsnapper.timer.j2
    dest: /etc/systemd/system/tarsnapper.timer
    mode: "0644"
  notify:
    - Reload systemd config
    - Restart tarsnapper

- name: Include nmtrust unit tasks
  ansible.builtin.include_tasks: roles/nmtrust/tasks/unit.yml
  vars:
    unit: tarsnapper.timer
    run_on: "{{ tarsnapper.run_on }}"
