---
- name: Install GNU Units
  kewlfft.aur.aur:
    name: units
    use: makepkg
    skip_pgp_check: true
  become: true
  become_user: "{{ aur.user }}"
  tags:
    - aur

- name: Include nmtrust unit tasks
  ansible.builtin.include_tasks: roles/nmtrust/tasks/unit.yml
  vars:
    unit: units_currency.timer
    run_on: "{{ units.run_on }}"
