---
- name: Install VirtualBox and dependencies
  community.general.pacman:
    name:
      - net-tools
      - virtualbox
      - virtualbox-guest-iso
      - virtualbox-host-dkms
    state: present

- name: Install VirtualBox extensions
  kewlfft.aur.aur:
    name: virtualbox-ext-oracle
  become: true
  become_user: "{{ aur.user }}"
  tags:
    - aur

- name: Add the user to vboxusers group
  ansible.builtin.user:
    name: "{{ user.name }}"
    groups: vboxusers
    append: true
  tags:
    - user
