---
- name: Install Tor
  community.general.pacman:
    name:
      - tor
      - torsocks
    state: present

- name: Include nmtrust unit tasks
  ansible.builtin.include_tasks: roles/nmtrust/tasks/unit.yml
  vars:
    unit: tor.service
    run_on: "{{ tor.run_on }}"
