---
- name: Install mpd
  community.general.pacman:
    name: mpd
    state: present

- name: Jail mpd
  ansible.builtin.file:
    src: /usr/bin/firejail
    dest: /usr/local/bin/mpd
    state: link
  tags:
    - firejail

- name: Verify mpd firejail local profile exists
  ansible.builtin.copy:
    content: ""
    dest: "/etc/firejail/mpd.local"
    force: false
    mode: "0644"
  tags:
    - firejail

- name: Set mpd firejail protocols
  ansible.builtin.lineinfile:
    dest: /etc/firejail/mpd.local
    regexp: "^protocol"
    line: "protocol unix,inet,inet6,netlink"
  tags:
    - firejail

- name: Push mpd service file
  ansible.builtin.copy:
    src: mpd.service
    dest: /etc/systemd/user/mpd.service
    mode: "0644"
  notify:
    - Reload systemd config
  tags:
    - firejail

- name: Install mpc
  community.general.pacman:
    name: mpc
    state: present

- name: Install ncmpcpp
  community.general.pacman:
    name: ncmpcpp
    state: present

- name: Jail ncmpcpp
  ansible.builtin.file:
    src: /usr/bin/firejail
    dest: /usr/local/bin/ncmpcpp
    state: link
  tags:
    - firejail

- name: Push ncmpcpp firejail profile
  ansible.builtin.copy:
    src: firejail/ncmpcpp.profile
    dest: /usr/local/etc/firejail/ncmpcpp.profile
    mode: "0644"
  notify:
    - Activate firejail profiles
  tags:
    - firejail
