---
- name: Install neomutt
  community.general.pacman:
    name: neomutt
    state: present

- name: Make neomutt available as mutt
  ansible.builtin.file:
    src: /usr/bin/neomutt
    dest: /usr/local/bin/mutt
    state: link

- name: Verify mutt firejail local profile exists
  ansible.builtin.copy:
    content: ""
    dest: /etc/firejail/mutt.local
    force: false
    mode: "0644"
  tags:
    - firejail

- name: Whitelist mutt related files
  ansible.builtin.blockinfile:
    dest: /etc/firejail/mutt.local
    block: |
      noblacklist ~/.config/vdirsyncer
      noblacklist ~/.config/pimsync
      noblacklist ~/.vdirsyncer
      noblacklist ~/.calendars
      noblacklist ~/.contacts
      noblacklist ~/.mbsyncrc
      noblacklist ~/.offlineimap
      noblacklist ~/.offlineimaprc
  tags:
    - firejail

- name: Install urlscan
  community.general.pacman:
    name: urlscan

- name: Install notmuch
  community.general.pacman:
    name: notmuch
    state: present

- name: Install mutt-ics
  kewlfft.aur.aur:
    name: mutt-ics
  become: true
  become_user: "{{ aur.user }}"
  tags:
    - aur

- name: Push mutt-mailto script
  ansible.builtin.copy:
    src: mutt-mailto.sh
    dest: /usr/local/bin/mutt-mailto
    mode: "0755"

- name: Create local desktop application dir
  ansible.builtin.file:
    path: /usr/local/share/applications
    state: directory
    mode: "0755"

- name: Push mutt desktop file
  ansible.builtin.copy:
    src: mutt.desktop
    dest: /usr/local/share/applications/mutt.desktop
    mode: "0644"

- name: Verify mimeapps.list exists
  ansible.builtin.copy:
    content: ""
    dest: /etc/xdg/mimeapps.list
    force: false
    mode: "0644"

- name: Set mutt as default application for mailto links
  ansible.builtin.lineinfile:
    dest: /etc/xdg/mimeapps.list
    regexp: "^x-scheme-handler/mailto="
    line: "x-scheme-handler/mailto=mutt.desktop"

- name: Include msmtp tasks
  ansible.builtin.include_tasks: msmtp.yml
- name: Include isync tasks
  ansible.builtin.include_tasks: isync.yml
# - ansible.builtin.include_tasks: offlineimap.yml
- name: Include mailsync tasks
  ansible.builtin.include_tasks: mailsync.yml
- name: Include oauth2 tasks
  ansible.builtin.include_tasks: oauth2.yml
