---
- name: Install KDE Connect
  community.general.pacman:
    name: kdeconnect
    state: present

- name: Push KDE Connect service file
  ansible.builtin.template:
    src: kdeconnect.service.j2
    dest: /etc/systemd/user/kdeconnect.service
    mode: "0644"
  notify:
    - Reload systemd config

- name: Include nmtrust unit tasks
  ansible.builtin.include_tasks: roles/nmtrust/tasks/unit.yml
  vars:
    unit: kdeconnect.service
    run_on: "{{ kdeconnect.run_on }}"
    user_unit: true
