---
- name: Add plugdev group
  ansible.builtin.group:
    name: plugdev
    state: present

- name: "Add user to plugdev group: {{ user.name }}"
  ansible.builtin.user:
    name: "{{ user.name }}"
    groups: plugdev
    append: true
  tags:
    - user

- name: Install Solaar
  community.general.pacman:
    name: solaar
    state: present
