---
- name: Install cdrtools
  community.general.pacman:
    name: cdrtools
    state: present

- name: Install dvd+rw-tools
  community.general.pacman:
    name: dvd+rw-tools
    state: present

- name: Install xfburn
  community.general.pacman:
    name: xfburn
    state: present
