---
- name: Install parcimonie.sh
  kewlfft.aur.aur:
    name: parcimonie-sh-git
    use: makepkg
    skip_pgp_check: true
  become: true
  become_user: "{{ aur.user }}"
  tags:
    - aur

- name: Push parcimonie.sh user configuration
  ansible.builtin.template:
    src: user.conf.j2
    dest: /etc/parcimonie.sh.d/{{ user.name }}.conf
    mode: "0644"

- name: Include nmtrust unit tasks
  ansible.builtin.include_tasks: roles/nmtrust/tasks/unit.yml
  vars:
    unit: "parcimonie.sh@{{ user.name }}.service"
    run_on: "{{ tor.run_on }}"
