---
- name: Install firejail
  community.general.pacman:
    name: firejail
    state: present

- name: Install firewarden
  kewlfft.aur.aur:
    name: firewarden
  become: true
  become_user: "{{ aur.user }}"
  tags:
    - aur

- name: Install firejail profile update script
  ansible.builtin.copy:
    src: profile-activate.sh
    dest: /usr/local/bin/profile-activate
    mode: "0755"

- name: Create firejail profile directory
  ansible.builtin.file:
    path: /usr/local/etc/firejail
    state: directory
    mode: "0755"

- name: Verify firejail globals file exists
  ansible.builtin.copy:
    content: ""
    dest: /etc/firejail/globals.local
    force: false
    mode: "0644"

- name: Add blacklist to globals
  ansible.builtin.lineinfile:
    dest: /etc/firejail/globals.local
    state: present
    line: "blacklist {{ item }}"
  with_items: "{{ firejail.blacklist }}"

- name: Verify firejail users file exists
  ansible.builtin.copy:
    content: ""
    dest: /etc/firejail/firejail.users
    force: false
    mode: "0644"

- name: Add user to firejail users
  ansible.builtin.lineinfile:
    dest: /etc/firejail/firejail.users
    state: present
    line: "{{ user.name }}"
