---
- name: Install pipenv
  community.general.pacman:
    name: python-pipenv
    state: present

- name: Install pyenv
  community.general.pacman:
    name: pyenv
    state: present

- name: Install ruff
  community.general.pacman:
    name: ruff
    state: present

- name: Install uv
  community.general.pacman:
    name: uv
    state: present

- name: Install documentation
  community.general.pacman:
    name: python-docs
    state: present
