---
- name: Install poppler-glib
  community.general.pacman:
    name: poppler-glib
    state: present
  tags:
    - gimp

- name: Install GIMP
  community.general.pacman:
    name:
      - gimp
      - gimp-plugin-gmic
    state: present
  tags:
    - gimp

- name: Jail GIMP
  ansible.builtin.file:
    src: /usr/bin/firejail
    dest: /usr/local/bin/gimp
    state: link
  tags:
    - gimp
    - firejail
