---
- name: Include beets tasks
  ansible.builtin.include_tasks: beets.yml
- name: Include ImageMagick tasks
  ansible.builtin.include_tasks: imagemagick.yml
- name: Include Inkscape tasks
  ansible.builtin.include_tasks: inkscape.yml
- name: Include GIMP tasks
  ansible.builtin.include_tasks: gimp.yml
- name: Include gThumb tasks
  ansible.builtin.include_tasks: gthumb.yml
- name: Include feh tasks
  ansible.builtin.include_tasks: feh.yml
- name: Include imv tasks
  ansible.builtin.include_tasks: imv.yml
- name: Include teiler tasks
  ansible.builtin.include_tasks: teiler.yml
- name: Include flac2all tasks
  ansible.builtin.include_tasks: flac2all.yml
- name: Include Darktable tasks
  ansible.builtin.include_tasks: darktable.yml
- name: Include qcode tasks
  ansible.builtin.include_tasks: qcode.yml

- name: Install misc media codecs and helpers
  community.general.pacman:
    name:
      - flac
      - lame
      - gst-libav
      - gst-plugins-good
      - exiv2
      - perl-image-exiftool
      - perl-archive-zip
      - opus-tools
    state: present

- name: Install Metadata Anonymisation Toolkit
  community.general.pacman:
    name: mat2
    state: present
  tags:
    - mat

- name: Install yt-dlp
  community.general.pacman:
    name:
      - yt-dlp
      - yt-dlp-ejs
    state: present

- name: Install zbar
  community.general.pacman:
    name: zbar
    state: present

- name: Install sxiv
  community.general.pacman:
    name: sxiv
    state: present

- name: Install svgcleaner
  community.general.pacman:
    name: svgcleaner
    state: present

- name: Install flameshot
  community.general.pacman:
    name: flameshot
    state: present

- name: Install digikam
  community.general.pacman:
    name: digikam
    state: present

- name: Install whipper
  community.general.pacman:
    name: whipper
    state: present
