---
- name: Install pianobar
  community.general.pacman:
    name: pianobar
    state: present

- name: Jail pianobar
  ansible.builtin.file:
    src: /usr/bin/firejail
    dest: /usr/local/bin/pianobar
    state: link
  tags:
    - firejail

- name: Push pianobar firejail profile
  ansible.builtin.copy:
    src: firejail/pianobar.profile
    dest: /usr/local/etc/firejail/pianobar.profile
    mode: "0644"
  notify:
    - Activate firejail profiles
  tags:
    - firejail
