---
- name: Install fprintd
  community.general.pacman:
    name: fprintd
    state: present
  tags:
    - fingerprint

- name: Push sudo authentication file
  ansible.builtin.template:
    src: pam.d/sudo.j2
    dest: /etc/pam.d/sudo
    mode: "0644"
  tags:
    - fingerprint

- name: Push i3lock authentication file
  ansible.builtin.template:
    src: pam.d/i3lock.j2
    dest: /etc/pam.d/i3lock
    mode: "0644"
  tags:
    - fingerprint

- name: Push trackpoint udev rules
  ansible.builtin.copy:
    src: 10-trackpoint.rules
    dest: /etc/udev/rules.d/10-trackpoint.rules
    mode: "0644"
  tags:
    - trackpoint
