---
- name: Install fprintd
  pacman: name=fprintd state=present
  tags:
    - fingerprint

- name: Push sudo authentication file
  template: src=pam.d/sudo.j2 dest=/etc/pam.d/sudo
  tags:
    - fingerprint

- name: Push i3lock authentication file
  template: src=pam.d/i3lock.j2 dest=/etc/pam.d/i3lock
  tags:
    - fingerprint

- name: Push trackpoint udev rules
  copy: src=10-trackpoint.rules dest=/etc/udev/rules.d/10-trackpoint.rules
  tags:
    - trackpoint
