---
- name: Install zip archive utilities
  community.general.pacman:
    name:
      - zip
      - unzip
      - 7zip
    state: present
  tags:
    - zip

- name: Install unrar
  community.general.pacman:
    name: unrar
    state: present
  tags:
    - unrar

- name: Install atool
  community.general.pacman:
    name: atool
    state: present
  tags:
    - atool

- name: Install par2cmdline
  community.general.pacman:
    name: par2cmdline
    state: present
  tags:
    - par2

- name: Install ddrescue
  community.general.pacman:
    name: ddrescue
    state: present
  tags:
    - ddrescue

- name: Install lesspipe
  community.general.pacman:
    name: lesspipe
    state: present
  tags:
    - lesspipe

- name: Install libisoburn
  community.general.pacman:
    name: libisoburn
    state: present
  tags:
    - libisoburn

- name: Install pigz
  community.general.pacman:
    name: pigz
    state: present
  tags:
    - pigz

- name: Install ventoy
  kewlfft.aur.aur:
    name: ventoy-bin
  become: true
  become_user: "{{ aur.user }}"
  tags:
    - aur
    - ventoy
