---
- name: Install greenclip from AUR
  kewlfft.aur.aur:
    name: rofi-greenclip
  become: true
  become_user: "{{ aur.user }}"
  tags:
    - aur

- name: Copy greenclip.service
  ansible.builtin.copy:
    src: greenclip.service
    dest: /etc/systemd/user/greenclip.service
    mode: "0644"

- name: Enable greenclip.service
  ansible.builtin.systemd:
    name: greenclip.service
    scope: user
    enabled: true
    state: started
  become: true
  become_user: "{{ user.name }}"
  environment:
    XDG_RUNTIME_DIR: "/run/user/{{ user.uid }}"
