---
- name: Install GNUradio
  community.general.pacman:
    name: gnuradio
    state: present

- name: Install hamlib
  community.general.pacman:
    name: hamlib
    state: present

- name: Include RTL-SDR tasks
  ansible.builtin.include_tasks: rtl-sdr.yml
- name: Include radio ops tasks
  ansible.builtin.include_tasks: radio_ops.yml
# - ansible.builtin.include_tasks: radio_mgmt.yml
