---
- name: Install universal base packages
  community.general.pacman:
    name: "{{ base_packages }}"
    state: present
  tags:
    - packages

- name: Create pacman hook directory
  ansible.builtin.file:
    path: /etc/pacman.d/hooks
    state: directory
    mode: "0755"
  tags:
    - packages

- name: Use all cores when compressing packages
  ansible.builtin.lineinfile:
    dest: /etc/makepkg.conf
    regexp: "^COMPRESSXZ"
    line: "COMPRESSXZ=(xz -c -z - --threads=0)"

- name: Install AUR base packages
  kewlfft.aur.aur:
    name: "{{ aur.packages }}"
  become: true
  become_user: "{{ aur.user }}"
  tags:
    - aur
    - packages

- name: Push pacman cache cleanup service
  ansible.builtin.copy:
    src: paccache.service
    dest: /etc/systemd/system/paccache.service
    mode: "0644"
  notify:
    - Reload systemd config
  tags:
    - packages

- name: Push pacman cache cleanup timer
  ansible.builtin.copy:
    src: paccache.timer
    dest: /etc/systemd/system/paccache.timer
    mode: "0644"
  notify:
    - Reload systemd config
    - Restart paccache
  tags:
    - packages

- name: Enable and start pacman cache cleanup timer
  ansible.builtin.service:
    name: paccache.timer
    enabled: true
    state: started
  tags:
    - packages
