---
- name: Install Bash
  community.general.pacman:
    name:
      - bash
      - bash-completion
    state: present
  tags:
    - shell

- name: Install ZSH
  community.general.pacman:
    name:
      - zsh
      - zsh-completions
    state: present
  tags:
    - shell

- name: Install Starship
  community.general.pacman:
    name:
      - ttf-nerd-fonts-symbols-mono
      - starship
    state: present
  tags:
    - shell

- name: Install zsh-antidote
  kewlfft.aur.aur:
    name: zsh-antidote
  become: true
  become_user: "{{ aur.user }}"
  tags:
    - aur
