---
- name: Install alsa-utils
  community.general.pacman:
    name: alsa-utils
    state: present

- name: Install sof-firmware
  community.general.pacman:
    name: sof-firmware
    state: present

- name: Install Pipewire
  community.general.pacman:
    name:
      - pipewire
      - pipewire-pulse
      - pavucontrol
    state: present

- name: Install pasystray
  community.general.pacman:
    name: pasystray
    state: present

- name: Install easyeffects
  community.general.pacman:
    name: easyeffects
    state: present

- name: Install Linux Studio Plugins
  community.general.pacman:
    name: lsp-plugins
    state: present

- name: Install calf studio gear
  community.general.pacman:
    name: calf
    state: present
