---
- name: Install xautolock
  kewlfft.aur.aur:
    name: xautolock
  become: true
  become_user: "{{ aur.user }}"
  tags:
    - aur

- name: Install i3lock
  community.general.pacman:
    name: i3lock
    state: present

- name: Push lock script
  ansible.builtin.copy:
    src: lock.sh
    dest: /usr/local/bin/lock
    mode: "0755"

- name: Push screen lock service file
  ansible.builtin.copy:
    src: screenlock.service
    dest: /etc/systemd/system/screenlock@.service
    mode: "0644"
  notify:
    - Reload systemd config

- name: Enable screen lock service
  ansible.builtin.service:
    name: "screenlock@{{ user.name }}.service"
    enabled: true
