---
- name: Install magic-wormhole
  community.general.pacman:
    name: magic-wormhole
    state: present

- name: Jail magic-wormhole
  ansible.builtin.file:
    src: /usr/bin/firejail
    dest: /usr/local/bin/wormhole
    state: link
  tags:
    - firejail

- name: Push magic-wormhole firejail profile
  ansible.builtin.copy:
    src: firejail/wormhole.profile
    dest: /usr/local/etc/firejail/wormhole.profile
    mode: "0644"
  notify:
    - Activate firejail profiles
  tags:
    - firejail
