---
- name: Install NetworkManager and dependencies
  community.general.pacman:
    name:
      - networkmanager
      - networkmanager-openvpn
      - network-manager-applet
      - xfce4-notifyd
      - gnome-keyring
    state: present

- name: Push connectivity check config
  ansible.builtin.template:
    src: connectivity.conf.j2
    dest: /etc/NetworkManager/conf.d/20-connectivity.conf
    mode: "0644"

- name: Push MAC address randomization config
  ansible.builtin.template:
    src: random_mac.conf.j2
    dest: /etc/NetworkManager/conf.d/20-random_mac.conf
    mode: "0644"

- name: Push WiFi/Wired Exclusive dispatcher
  ansible.builtin.copy:
    src: wifi-wired-exclusive.sh
    dest: /etc/NetworkManager/dispatcher.d/70-wifi-wired-exclusive
    mode: "0755"
  when: network.wifi_wired_exclusive is defined and network.wifi_wired_exclusive

- name: Enable and start NetworkManager
  ansible.builtin.service:
    name: NetworkManager.service
    enabled: true
    state: started

- name: Enable and start NetworkManager dispatcher
  ansible.builtin.service:
    name: NetworkManager-dispatcher.service
    enabled: true
    state: started

- name: Disable dhcpcd service
  ansible.builtin.service:
    name: dhcpcd.service
    enabled: false
