---
- name: Install Vopono
  kewlfft.aur.aur:
    name: vopono
  become: true
  become_user: "{{ aur.user }}"
  tags:
    - aur

- name: Allow passwordless Vopono for wheel group
  ansible.builtin.copy:
    src: sudo_vopono
    dest: /etc/sudoers.d/03_vopono
    mode: "0440"
    validate: "visudo -cf %s"
  tags:
    - aur
    - sudo
