---
- name: Install aria2
  community.general.pacman:
    name: aria2
    state: present

- name: Jail aria2
  ansible.builtin.file:
    src: /usr/bin/firejail
    dest: /usr/local/bin/aria2c
    state: link
  tags:
    - firejail
