---
- name: Add Infinality repository to pacman
  command: bash -c "if ! grep -q bohoomil.com/repo /etc/pacman.conf; then printf '\n[infinality-bundle]\nServer = http://bohoomil.com/repo/$arch\n' >> /etc/pacman.conf; fi"
  tags:
    - infinality

- name: Verify root gnupg directory exists
  file: path=/root/.gnupg/ state=directory
  tags:
    - infinality

- name: Verify dirmngr is configured
  file: path=/root/.gnupg/dirmngr_ldapservers.conf state=touch
  tags:
    - infinality

- name: Verify dirmngr is running
  command: dirmngr
  tags:
    - infinality

- name: Install Infinality repository key
  command: pacman-key -r AE6866C7962DDE58
  tags:
    - infinality

- name: Trust Infinality repository key
  command: pacman-key --lsign-key AE6866C7962DDE58
  tags:
    - infinality

- name: Update package cache
  pacman: update_cache=yes
  tags:
    - infinality

- name: Install Infinality bundle
  pacman: name={{ item }} state=present
  with_items:
    - freetype2-infinality-ultimate
    - fontconfig-infinality-ultimate
    - cairo-infinality-ultimate
  tags:
    - infinality
